#Correcting errors
- name: Creates directory to correct misconfiguration on cgroup
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root

- name: Copy file with correct configuration
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart docker

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Copy the join command to {{ k8s_cluster_name }} cluster
  copy: 
    src: "./{{ k8s_cluster_name }}-join-command" 
    dest: /home/{{ k8s_node_admin_user }}/{{ k8s_cluster_name }}-join-command
    owner: "{{ k8s_node_admin_user }}"
    group: "{{ k8s_node_admin_group }}"
    mode: 0760  

- name: Join the node to cluster {{ k8s_cluster_name }}
  command: sh /home/{{ k8s_node_admin_user }}/{{ k8s_cluster_name }}-join-command
