- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: restart docker
  become: true
  service:
    name: docker 
    state: restarted 
    daemon_reload: yes

- name: restart kubelet
  become: true
  service: 
    name: kubelet 
    state: restarted 
    daemon_reload: yes
